# syntax = docker/dockerfile:experimental
FROM nginx:stable
WORKDIR /usr/share/nginx/html/
RUN --mount=type=bind,from=web-team-pre:latest,source=/app/dist,target=/tmp/dist ls /tmp/dist && mkdir -p /usr/share/nginx/html && cp -r /tmp/dist/* /usr/share/nginx/html/
ADD ./docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
COPY ./docker/entrypoint.sh /
CMD ["bash", "/entrypoint.sh"]